Use FlakeHub links in README
DeterminateSystems/nuenv pull request #26
Opened 2024-05-01 17:48 UTC by lucperkins

2024-05-01 21:16 UTC, cole-h requested changes

2024-05-01 21:16 UTC, cole-h commented on README.md
> +    nuenv.url = "https://:flakehub.com/f/DeterminateSystems/nuenv/*.tar.gz";
```suggestion
    nuenv.url = "https://flakehub.com/f/DeterminateSystems/nuenv/*.tar.gz";
```

2024-05-01 21:16 UTC, cole-h commented on README.md
> +    nuenv.url = "https://:flakehub.com/f/DeterminateSystems/nuenv/*.tar.gz";
```suggestion
    nuenv.url = "https://flakehub.com/f/DeterminateSystems/nuenv/*.tar.gz";
```

2024-05-03 17:48 UTC, lucperkins commented on README.md
> +    nuenv.url = "https://:flakehub.com/f/DeterminateSystems/nuenv/*.tar.gz";
Derp

2024-05-03 18:02 UTC, cole-h approved these changes

2024-05-03 18:44 UTC, merged